server:
  port: 8081
spring:
  thymeleaf:
    prefix: classpath:/templates/
    redis:
        host: 192.168.18.1
        password:
        port: 6379
        pool:
          max-idle: 100
          min-idle: 1
          max-active: 1000
          max-wait: -1
